version: '3.8'

services:
  c3check_app:
    build:
      context: .
      dockerfile: Dockerfile
    image: php:8.4-fpm
    container_name: c3check_app
    working_dir: /var/www
    volumes:
      - .:/var/www
    depends_on:
      - c3check_db
      - c3check_node
    networks:
      - c3check_net

  c3check_node:
    image: node:18
    container_name: c3check_node
    working_dir: /var/www
    volumes:
      - .:/var/www
    command: tail -f /dev/null
    ports:
      - "5181:5173"
    networks:
      - c3check_net

  c3check_nginx:
    depends_on:
      - c3check_app
    image: nginx:alpine
    container_name: c3check_nginx
    ports:
      - "8085:80"
    volumes:
      - .:/var/www
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - c3check_net

  c3check_db:
    image: mysql:8.0
    container_name: c3check_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: c3check
      MYSQL_USER: c3check_user
      MYSQL_PASSWORD: c3check_pass
    ports:
      - "3308:3306"
    volumes:
      - dbdata_c3check:/var/lib/mysql
    networks:
      - c3check_net

networks:
  c3check_net:

volumes:
  dbdata_c3check:
